version: '2'
services:
  odoo:
    #image: docker.io/bitnami/odoo:16
    env_file: .env
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql
    ports:
      - '127.0.0.1:8069:8069'
      - '127.0.0.1:5678:5678'
    volumes:
      - 'odoo_data:/bitnami/odoo'
#      - ./addons:/mnt/extra-addons
      - ./addons:/bitnami/odoo/addons     
  postgresql:
    image: docker.io/bitnami/postgresql:15
    env_file: .env
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
volumes:
  odoo_data:
    driver: local
  postgresql_data:
    driver: local
